/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestNative */

#ifndef _Included_TestNative
#define _Included_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestNative
 * Method:    foo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestNative_foo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
